### ISSUE TITLE
File Chooser not working on API 19

### ISSUE THREAD

**Issue by AyushiBShah** [vic797/prowebview#1]
File chooser isn't opening for kitkat devices in HTML form where filetype expected is an image .

**Comment by vic797** [comment]
I have no idea what is causing that. I will make a virtual device with KitKat to check this.

**Comment by AyushiBShah** [comment]
I did check with few virtual devices it doesn't seem to work for me. 
https://issuetracker.google.com/issues/36983532 This can be one of the reasons

**Comment by vic797** [comment]
I think I found a [possible solution](https://stackoverflow.com/questions/28600165/cant-open-file-chooser-in-webview-android-4-4-2-using-webchromeclient) that I need to test.

**Comment by AyushiBShah** [comment]
Hi , I tried the mentioned  din't seem to work for me. Please keep me posted incase it works for you.

**Comment by vic797** [comment]
After a research I found that ´onShowFileChooser´ method doesn't get called on API 19.

Also I added a method that may work on API <= 18.
