### ISSUE TITLE
How to stop redirect ?

### ISSUE THREAD

**Issue by adilove** [vic797/prowebview#10]
I can't stop redirect from inner links :(

**Comment by adilove** [comment]
ProWebView ignoring my return false

@Override
            public boolean shouldOverrideUrlLoading(ProWebView webView, String url) {
                return false;
            }

**Comment by vic797** [comment]
Ok... I think I fixed `shouldOverrideUrlLoading` but I don't know what are causing the redirects... What are you doing?
