### ISSUE TITLE
Looks like it doesn't handle url redirects

### ISSUE THREAD

**Issue by iRYO400** [vic797/prowebview#7]

**Comment by vic797** [comment]
Please be more specific :neutral_face:. What are you trying? I don't think I changed anything related to the redirection.

**Comment by iRYO400** [comment]
I have trouble with websites that support login via socials( G+, FB, VK, Twitter). 
Usually, it should open a new small window with login form of specific social. But I'm using only one WebView, so maybe you can make a new listener like in the link
https://stackoverflow.com/questions/4066438/android-webview-how-to-handle-redirects-in-app-instead-of-opening-a-browser

**Comment by smoochiee** [comment]
Yes some links cannot open...and login not redirecting..

**Comment by smoochiee** [comment]
Yes some links cannot open...and login not redirecting..

**Comment by vic797** [comment]
I'm trying to solve this problem in a way that doesn't affect other methods. I will update the project soon.
